export const GAME_TITLES = {
    "csgo": "CSGO",
    "minecraft": "Minecraft",
    "rust": "Rust",
    "dayz": "DayZ",
    "ark": "ARK: Survival Evolved",
    "gmod": "Garry's Mod",
    "cs": "Counter-Strike",
    "squad": "Squad",
    "unturned": "Unturned",
    "tf2": "Team Fortress 2",
    "hll": "Hell Let Loose",
    "arma3": "ArmA 3",
    "scum": "Scum",
    "css": "Counter-Strike: Source",
    "valheim": "Valheim",
    "7dtd": "7 Days to Die",
    "conanexiles": "Conan Exiles",
    "zomboid": "Project Zomboid",
    "vrising": "V Rising",
    "atlas": "Atlas",
    "moe": "Myth of Empires",
    "insurgency": "Insurgency",
    "rs2vietnam": "Rising Storm 2: Vietnam",
    "sandstorm": "Insurgency: Vietnam",
    "arma2": "ArmA 2",
    "postscriptum": "Post Scriptum",
    "mordhau": "MORDHAU",
    "dnl": "Dark and Light",
    "pixark": "PixARK",
    "btw": "Beyond the Wire",
    "battalion1944": "Battalion 1944",
    "rend": "Rend"
} as { [key: string]: string };