export const GameChoiceData = [
    { name: 'Counter-Strike: Global Offensive', value: 'csgo' },
    { name: 'Minecraft', value: 'minecraft' }, 
    { name: 'Rust', value: 'rust' },
    { name: 'DayZ', value: 'dayz' },
    { name: 'ARK: Survival Evolved', value: 'ark' },
    { name: 'Scum', value: 'scum' },
    { name: 'Squad', value: 'squad' },
    { name: 'Garry\'s Mod', value: 'gmod' },
    { name: 'V Rising', value: 'vrising' },
    { name: 'Counter-Strike', value: 'cs' },
    { name: 'Unturned', value: 'unturned' },
    { name: 'Team Fortress 2', value: 'tf2' },
    { name: 'ArmA 3', value: 'arma3' },
    { name: '7 Days to Die', value: '7dtd' },
    { name: 'Project Zomboid', value: 'zomboid' },
    { name: 'Counter-Strike: Source', value: 'css' },
    { name: 'Conan Exiles', value: 'conanexiles' },
    { name: 'Valheim', value: 'valheim' },
    { name: 'Myth of Empires', value: 'moe' },
    { name: 'Atlas', value: 'atlas' },
    { name: 'Insurgency', value: 'insurgency' },
    { name: 'MORDHAU', value: 'mordhau' },
    { name: 'Insurgency: Sandstorm', value: 'sandstorm' },
    { name: 'Rising Storm 2: Vietnam', value: 'rs2vietnam' },
    { name: 'ArmA 2', value: 'arma2' },
    { name: 'Post Scriptum', value: 'postscriptum' },
    { name: 'Dark and Light', value: 'dnl' },
    { name: 'PixARK', value: 'pixark' },
    { name: 'Battalion 1944', value: 'battalion1944' },
    { name: 'Beyond the Wire', value: 'btw' },
    { name: 'Rend', value: 'rend' },
];